### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Arnold1** [DomiStyle/docker-tor-browser#16]
Hi,

how to run multiple browsers?

the following doesn't work - is there a way to have another session on 5801?
```
docker run -d -p 5800:5800 domistyle/tor-browser
docker run -d -p 5801:5801 domistyle/tor-browser
```

**Comment by DomiStyle** [comment]
You only need to increment the host port, leave the container port as 5800 like this:

    docker run -d -p 5801:5800 domistyle/tor-browser

**Comment by Arnold1** [comment]
very cool - I can connect with any browser right?

**Comment by DomiStyle** [comment]
Yes, you can use any browser. If you forward port 5900 you can also use any VNC client.

You can copy/paste by using the clipboard function in the top right.

**Comment by Arnold1** [comment]
and after the clipboard submit?

**Comment by DomiStyle** [comment]
Just hit Ctrl + V or Right click -> Paste after copying text into the clipboard.

Yes, if you connect via http (directly to the container) you will see that your connection is unencrypted. If you run the container on your PC or on the same network you can ignore it. Otherwise, you should put it behind a reverse proxy.
