### ISSUE TITLE
How to check IP before connecting to TOR

### ISSUE THREAD

**Issue by daNutzzzzz** [DomiStyle/docker-tor-browser#58]
Hi,

If i try to access any website before connecting to TOR, it closes the browser and takes me back to the "Connect to TOR" page, how can i get around this so i can check my public IP before connecting to TOR?

**Comment by davidnewcomb** [comment]
The Tor browser is set up so that you can only send traffic over the tor network. This is a proxy and if you want to bypass it, you can. See [mozilla.cfg.template#L7](https://github.com/DomiStyle/docker-tor-browser/blob/master/browser-cfg/mozilla.cfg.template#L7) for an example of how to do this.

I would be very careful about opennig up any kind of DNS ports to give yourself the albility to "access any website".
